//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public int MaHoaDon { get; set; }
        public Nullable<int> MaDatPhong { get; set; }
        public int MaNV { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public decimal TongTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string LoaiHoaDon { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DatPhong DatPhong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
