//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiPhong
    {
        public LoaiPhong()
        {
            this.Phongs = new HashSet<Phong>();
        }
    
        public int MaLoaiPhong { get; set; }
        public string TenLoaiPhong { get; set; }
        public decimal GiaPhong { get; set; }
        public int SoGiuong { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual ICollection<Phong> Phongs { get; set; }
    }
}
