//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public Phong()
        {
            this.DatPhongs = new HashSet<DatPhong>();
        }
    
        public int MaPhong { get; set; }
        public string SoPhong { get; set; }
        public int MaLoaiPhong { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual ICollection<DatPhong> DatPhongs { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
    }
}
